### ISSUE TITLE
add CmdStan#master fails due to checkout error

### ISSUE THREAD

**Issue by ueliwechsler** [StanJulia/CmdStan.jl#101]
Not an urgent issue, but I just wanted to remark that adding the latest version of `CmdStan` does not work for me on Windows.

When I run
 `(@v1.5) pkg> add CmdStan#master`
I get the following error:
`ERROR: GitError(Code:ERROR, Class:Checkout, cannot checkout to invalid path 'examples_diffeqbayes/Predator-Prey Population Dynamics: the Lotka-Volterra model in Stan.pdf')`

There seems to be something wrong with that pdf file, since I also cannot extract the zipped version on Windows.

```julia
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
```

**Comment by goedman** [comment]
Thank you, will have a look into it and merge asap.

**Comment by goedman** [comment]
Could it be the spaces in the name of the file? Removed these in the latest master (to become v6.0.10 once fixed).

**Comment by goedman** [comment]
If this doesn't fix it I'll just remove the file as it just contains Bob C's write-up on Lotka-Volterra.

**Comment by goedman** [comment]
Hi @ueliwechsler 

If this indeed fixes it I must apologize, I should have paid attention to AppVeyer. Seems ok now.

Rob

**Comment by ueliwechsler** [comment]
Hi Rob,

Yes, it works again. Thank you very much for the quick fix!

Best,
Ueli
