### ISSUE TITLE
read_summary.jl may fail when no summary.csv file exists

### ISSUE THREAD

**Issue by gbarz** [StanJulia/CmdStan.jl#109]
I believe the update "Update read_summary.jl" on Aug 4 may have introduced an error, though it is only likely to be encountered when the "summary".csv file does not exists.  

Specifically, line 23 or read_summary.jl calls stan_summary(m) where m is a Stanmodel.  However, as I understand it, stan_summary requires two arguments. I.e.: stan_summary(model::Stanmodel, filecmd::Cmd; CmdStanDir=CMDSTAN_HOME). Consequently, read_summary throws the following error:  "> MethodError: no method matching stan_summary(::Stanmodel)

**Comment by goedman** [comment]
Thank you, think I checked this, but apparently not! As in your other issue (https://github.com/StanJulia/CmdStan.jl/issues/108#issue-806567628), which version of cmdstan are you using?

**Comment by gbarz** [comment]
I am presently using 2.23.0. I know your notes suggest cmdstan.jl may only work up thru 2.19, but it had been working until recently.  

The only reason I saw this, however, is because of the absence of the summary.csv file (as identified in #108)

**Comment by goedman** [comment]
Aah, I need to update that note. I believe this issue became a `real` issue in cmdstan v2.26. That's when I had to change the command switch.

As a work around you should be able to a previous version of CmdStan.jl. I'll dig a bit bit deeper this afternoon.
