### ISSUE TITLE
Legendre Polynomials

### ISSUE THREAD

**Issue by PToTheK** [StanJulia/CmdStan.jl#110]
Hi folks,
great work of yours! Many thanks to port Stan to Julia!

I would like to use [associated Legendre Polynomials](https://en.wikipedia.org/wiki/Associated_Legendre_polynomials) in order to compute the used regression function.

How do I do that?

**Comment by goedman** [comment]
This question is probably better for DiffEqBayes.jl, the TuringLang forums or the Stan forums.

**Comment by PToTheK** [comment]
First of all, thank you for your answer.

I found the Legendre Polynomials in the Boost-Library.
However, in which 'Stan block' do I put the 'inlcude statement'?
`#include <boost/math/special_functions/legendre.hpp>`

**Comment by goedman** [comment]
The include statement will need to be added to the make/build step (if this c++ file is not currently included).

The 2nd step needed is to define a function to use this special function. This will go in the functions block (the very first block in the Stan language model).

This function can then be used in e.g. the model block. An example can be found in [here](https://github.com/StanJulia/Stan.jl/blob/master/Examples_Stan_Methods/Parse_and_Interpolate_Example/example.jl).

**Comment by PToTheK** [comment]
Thank your very much for your answer!
Thanks for pointing out an example :)
