### ISSUE TITLE
Stanmodel not recognising unchanged model

### ISSUE THREAD

**Issue by andrstef** [StanJulia/CmdStan.jl#111]
When constructing a `Stanmodel`, I always get `File myfile.stan will be updated.` even when the model hasn't changed.
It seems, this comes from the fact that the `parse_and_interpolate` function always appends a newline `\n` at the end of the model string.
Hence, in function `update_model_file`, if `model` has *no* trailing `\n`, `model1` has *one* `\n` and is written out. Next time, `model2` then has *two* trailing `\n`. In the end, `model1` will never be equal to `model2`.
Guess, changing line 30 in `update_model_file.jl` to `model2 = parse_and_interpolate(strip(read(file, String)))` could help.

**Comment by goedman** [comment]
Thank you for the issue. Will have a look.

**Comment by goedman** [comment]
Pushing a fix for this in CmdStan v6.1.8. Should be available in about an hour or so.

**Comment by goedman** [comment]
Should be available now.

**Comment by andrstef** [comment]
Works like a charm, thanks a lot for the fast help!
