### ISSUE TITLE
Suggestion: `setenv(cmd; dir=target)` instead of `cd(target) do`

### ISSUE THREAD

**Issue by Byrth** [StanJulia/CmdStan.jl#114]
This is a more general suggestion and I do remember that CmdStan.jl is (or soon will be?) deprecated, but I'm putting it here because I'm most likely to make a PR related to it here after your feedback.

It is safer to use `run(setenv(cmd, ENV; dir=target))` than `cd(target) do run(cmd)` because cd() changes the caller's working directory (for all threads in a multithreaded situation) while `setenv(cmd, environment; dir=path)` only changes the working directory of the running command.

This is something of a continuation of the push towards absolute paths to make Stan safely usable in a parallel manner. Currently I use within-chain parallelization, which works pretty well, but fitting 4 models serially with 4 chains and 4 CPUs per chain is less CPU efficient (and slower) than fitting 4 models in parallel with 4 chains and 1 CPU per chain.

Here is a demo:
```bash
mkdir -p test
echo '#/!/bin/bash' > test/athing.sh
echo 'sleep 2' >> test/athing.sh
echo 'ls' >> test/athing.sh
chmod +x test/athing.sh

pwd

JULIA_NUM_THREADS=2 julia
# below is in the Julia REPL and should be run all at once
pwd()
@async run(setenv(`./athing.sh`, ENV; dir="test"))
pwd()
# Now it should print out the contents of the test directory we just made
```

Do you want me to switch the various `cd + run` commands to use this?

**Comment by goedman** [comment]
Hi @Byrth,

Thank you for looking into this and yes if you can update the examples using the `cd + run` approach, that would be great. 

Best,
Rob

**Comment by goedman** [comment]
Thanks a lot @Byrth. Will merge as v 6.2.0!

**Comment by Byrth** [comment]
No problem, thanks for the quick merge!

**Comment by goedman** [comment]
Thank you!

About 2 months after cmdstan v2.27.0 is released I'll try to set some time aside to update the Stan Language used in the examples, e.g. from the release notes:
```
 As opposed to the previously used syntax for arrays:

real a[5];
matrix[3,3] b[5];
vector[3] c[5];

we recommend switching to the new equivalent array syntax:

array[5] real a;
array[5] matrix[3,3] b;
array[5] vector[3] c;
```

At the same time I can update the examples to using `setenv()`.

**Comment by Byrth** [comment]
Hrm. I guess I missed what the examples were. 

Sorry about that. It is nice to see the updated `array[size]` syntax, though. I did not know that change had been made.

**Comment by goedman** [comment]
I meant e.g. the bernoulli.jl example in CmdStan.jl:
```
######### CmdStan program example  ###########

using CmdStan

ProjDir = @__DIR__
cd(ProjDir) do

  bernoullimodel = "
  data { 
    int<lower=1> N; 
    int<lower=0,upper=1> y[N];
  } 
  parameters {
    real<lower=0,upper=1> theta;
  } 
  model {
    theta ~ beta(1,1);
    y ~ bernoulli(theta);
  }
  ";

  observeddata = Dict("N" => 10, "y" => [0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

  # Preserve these variables outside cd/do block.
  global stanmodel, rc, samples, cnames, df
    
  stanmodel = Stanmodel(name="bernoulli", model=bernoullimodel,
    printsummary=false);

  rc, samples, cnames = stan(stanmodel, observeddata, ProjDir, CmdStanDir=CMDSTAN_HOME);
  
  if rc == 0
    # Fetch cmdstan summary as a DataFrame
    df = read_summary(stanmodel)

    df |> display
    println()

    df[df.parameters .== :theta, [:mean, :ess, :r_hat]] |> display
  end

end # cd block
```
But I guess that is still ok.

**Comment by Byrth** [comment]
yes, I believe that they now no longer need the `cd()` block, but it also doesn't hurt because it controls where the tmp directory gets made.
