### ISSUE TITLE
runlog and out.txt save to wrong location

### ISSUE THREAD

**Issue by itsdfish** [StanJulia/CmdStan.jl#119]
Hi Rob, 

Hopefully,  this is not user error this time. run.log and out.txt save to project_dir rather than project_dir/temp. I'm not sure if this is intentional, but I think it would be better to save to the temp folder. Here is a MWE:

```
using CmdStan

ProjDir = @__DIR__
cd(ProjDir)
stan_path = "/home/dfish/cmdstan"


  bernoullimodel = "
  data { 
    int<lower=1> N; 
    int<lower=0,upper=1> y[N];
  } 
  parameters {
    real<lower=0,upper=1> theta;
  } 
  model {
    theta ~ beta(1,1);
    y ~ bernoulli(theta);
  }
  ";

  observeddata = Dict("N" => 10, "y" => [0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

  # Preserve these variables outside cd/do block.
  global stanmodel, rc, samples, cnames, df
    
  stanmodel = Stanmodel(name="bernoulli", model=bernoullimodel,
    printsummary=false, output_format = :mcmcchains);

  rc, samples, cnames = stan(stanmodel, observeddata, ProjDir,
    CmdStanDir=stan_path);
```

**Comment by itsdfish** [comment]
Thanks for getting back to me. I am switching to stansample. The only thing
that threw me off is that nchains is a vector. Is there a reason for that?

**Comment by goedman** [comment]
I believe I can't change it later on after the SampleModel is created. I would love to get rid of this and just turn it into an Int.
