### ISSUE TITLE
fail if data is not of the comforming type, allow a single `Dict` 

### ISSUE THREAD

**Issue by tpapp** [StanJulia/CmdStan.jl#28]
Currently, `stan` fails if `data isa Dict`, since [this branch](https://github.com/StanJulia/CmdStan.jl/blob/master/src/main/stancode.jl#L115) will be just silently skipped. The user learns about this from the Stan error message that data is missing.

Suggestion: validate accepted `data` at the beginning.

Also, perhaps allow `data::Dict` instead of `[data]`, as the most common scenario is using the same data for all chains.

The first point also applies to `init`.

**Comment by goedman** [comment]
Thank you @tpapp I'll fix it!

**Comment by goedman** [comment]
I believe this is fixed now in CmdStan v4.5.0. Thanks again for reporting this.
