### ISSUE TITLE
Support for vector parameters

### ISSUE THREAD

**Issue by th0br0** [StanJulia/CmdStan.jl#33]
As per https://mc-stan.org/docs/2_18/stan-users-guide/linear-regression.html it is recommended to use matrix notation for data because this will be sped up via vectorisation.

While multi-dimensional arrays can be passed to Stan via the data dictionary, there is no way to access a results vector from Julia.
The vector is apparently filtered out at some point - neither `cnames` nor `values` provide a means to 
access. Specifying `beta[1]` as monitor also does not work, this issue appears to be independent of using `StanMCMCChain` (`:namedarray` also does not work)

I'd be happy to investigate / provide a PR on my own if I am pointed in the right direction, though I'm not sure if there's a 'good' solution to this given that a multidimensional array is not a sufficiently complex type.

**Expected behaviour:**
`beta` columns can be accessed via Julia

**Example repro:**
```julia
using CmdStan
using StanMCMCChain
using MCMCChain

y = collect(1:100);
x = [3:3:300 5:5:500];


model = """
data {
  int<lower = 0> N;
  int<lower = 0> k;
  matrix[N, k] x;
  real<lower=0> y[N];
}
parameters {
  vector[k] beta; 
  real<lower=0> sigma;
}
model {
  y ~ normal(x * beta, sigma);
}
""";
data = Dict("N"=>100, "k" => 2, "x" => x, "y" => y);
stanmodel = Stanmodel(monitors = ["beta", "sigma"],model=model,
  output_format=:mcmcchain);
rc, sim, cnames = stan(stanmodel, data; diagnostics = false);

cnames
# ["sigma"]

describe(sim)
```

**Comment by th0br0** [comment]
Closing; forgot that R tends to turn these indices into e.g. `beta.1` - specifying this via monitors works.

**Comment by goedman** [comment]
Although I have never figured out a better way to simplify capturing such an array and the dotted notation is awkward in Julia (I usually rename them to `beta_1` or even `beta[1]`, but it continues to bother me).

In the master version of (the still unregistered) StanMCMCChains.jl I'm experimenting with [m12.6sl](https://github.com/StanJulia/StanMCMCChains.jl/blob/master/examples/m12.6sl/m12.6sl.jl) and the new section option in (the not yet merged) MCMCChains.jl. Just as an example where we could go, this is still a number of weeks out ...

Any thoughts are welcome!

**Comment by oliverdechant** [comment]
> Closing; forgot that R tends to turn these indices into e.g. `beta.1` - specifying this via monitors works - apologies for the noise.

Would you mind sharing the code for this?

**Comment by goedman** [comment]
Hi Oliver, an example is [m10.04s.jl](https://github.com/StatisticalRethinkingJulia/StanModels.jl/blob/master/scripts/10/m10.04s.jl)
