### ISSUE TITLE
Change iteration range for chain

### ISSUE THREAD

**Issue by itsdfish** [StanJulia/CmdStan.jl#42]
Hi Rob-

I encountered an issue with the iteration range while trying to concatenate chains from different [samplers](https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/issues/19#issuecomment-498645385). CmdStan ignores the the warmup samples, as shown here:

```
Iterations        = 1:1000
Thinning interval = 1
Chains            = 1
Samples per chain = 1000
internals         = lp__, accept_stat__, stepsize__, treedepth__, n_leapfrog__, divergent__, energy__
parameters        = mu, sigma
```

Other samplers include the warmup iterations in the rage: 

```
Iterations        = 1001:2000
Thinning interval = 1
Chains            = 1
Samples per chain = 1000
internals         = lp__, accept_stat__, stepsize__, treedepth__, n_leapfrog__, divergent__, energy__
parameters        = mu, sigma
```
It is not possible to concatenate the chains because the ranges differ. As a work around, I tried to modify the range but encountered the following error:

`setfield! immutable struct of type Axis cannot be changed`

I was wondering if you would be able to change the iteration range so that it is consistent with the other samplers?

**Comment by goedman** [comment]
Hi Chris, I'll have a look this afternoon. Should not be too hard. Catching up with being back home in CO!

**Comment by goedman** [comment]
Hi Chris, should be fixed now. By default it will start with sample num_warmups+1.

For now in master. Unfortunately Travis is refusing to run the docs section. I am not sure how soon I can fix that as this ran perfectly fine up till a few weeks ago.

**Comment by itsdfish** [comment]
Much appreciated and welcome back to CO!

**Comment by goedman** [comment]
Do you use the start keyword for DynamicHMC? i did update DynamicHMCModels.create_mcmcchain but did not update master yet.

**Comment by itsdfish** [comment]
No. I couldn't find much information about start. Is it different from start_progress?

**Comment by goedman** [comment]
Ooh, sorry, I meant when you create an MCMCChains.Chains object there is an optional ‘start=…’ keyword which I now set by default to num_warmups+1 in CmdStan. We probably need something similar for dHMC.

**Comment by itsdfish** [comment]
Ok. I understand now. MCMCChains automatically sets the range when the adaption samples are removed.  For example` chain = chain[(Nadapt+1):end,:,:]` will set the iteration range 1001:2000 in our case. This is why it was conflicting with CmdStan, which was 1:1000 even though adaption samples were removed.

**Comment by goedman** [comment]
Correct, it does this by basically creating a new Chains object. I don’t understand why (immutable) AxisArrays were selected as the foundation for MCMCChains.Chains objects.

**Comment by itsdfish** [comment]
Indeed. It does seem to complicate certain things.

**Comment by itsdfish** [comment]
Hi Rob-

I encountered another issue. Hopefully the fix will be simple. The iteration range is correct when `save_warmup = false`. However, when `save_warmup=true`, the iterations and samplers per chain are off:


```
Iterations        = 1001:4000
Thinning interval = 1
Chains            = 1
Samples per chain = 3000
internals         = lp__, accept_stat__, stepsize__, treedepth__, n_leapfrog__, divergent__, energy__
parameters        = mu, sigma

2-element Array{ChainDataFrame,1}
```
The result above is based on the following configuration: 

```
CmdStanConfig = Stanmodel(name = "CmdStanGaussian",model=CmdStanGaussian,nchains=1,
   Sample(num_samples=2000,num_warmup=1000,adapt=CmdStan.Adapt(delta=0.8),
   save_warmup = true))
```

I believe the correct output should be:

```
Iterations        = 1:2000
Thinning interval = 1
Chains            = 1
Samples per chain = 2000
internals         = elapsed, epsilon, eval_num, lf_eps, lf_num, lp
parameters        = sigma, mu
```

**Comment by goedman** [comment]
Yip, my mistake ... will fix it.

**Comment by goedman** [comment]
Can you please try CmdStan master? I'm holding off registering v5.0.5 until I incorporate Tamas' suggestions to get the examples running on Travis.

After the little [exchange](https://discourse.julialang.org/t/help-with-travis-yml/25017/4?u=goedman) with Tamas I'm considering to start workin on CmdStan.jl v6.0.0 based on StanDump, StanRun and (possibly) StanSamples.jl.

Another thought I have been mulling over is to switch the next release of StatisticalRethinking over to DynamicHMC and PGFPlotsX. First part (dHMC) is pretty solid, second part (PGFPlotsX) I'm testing out for some other work I need to complete over the next few weeks.

**Comment by itsdfish** [comment]
Looks good. Thanks, Rob!

I should be able to add the cross-sampler rhat to MCMCBenchmarks. 

I have heard that PGFPlotsX is faster than Plots.jl. I'm guessing it has fewer features?

**Comment by goedman** [comment]
It's not really the speed that bothers me, neither PyPlot nor GR run reliably anymore on OSX. Both crash Julia.

I hesitate about PGFPlotsX for StatisticalRethinking because MCMCChains is married to Plots.jl and in fact as long as I make sure to use savefig() for each plot in GR (so it does not pop up a GKSTerm) it does work.

Don't know if it has fewer features. It does have easier support for greek/latin characters.

**Comment by itsdfish** [comment]
My main gripe is that it is painfully slow. I also had a few problems on OSX, but managed to get it working. What problem are you having?

**Comment by goedman** [comment]
What happens on my system GR produces the plot, shows it in GKSTerm and then Julia (the REPL) hangs and takes up many CPU cycles. I have to go into the ActivityMonitor and kill the julia process.

This happens not all the time, maybe once in every 2 or 3 plots. Or the GKSTerm crashes and won't show up until I restart Julia.

I am wondering if it might have something to do with memory constraints.

And yes, the first time it is really slow, but after that it's ok.

**Comment by itsdfish** [comment]
Bummer. It seems like your problem was different than mine. I use OSX at work and Ubuntu at home and have been surprised that Ubuntu has been less problematic.
