### ISSUE TITLE
Resource busy or locked

### ISSUE THREAD

**Issue by virgodi** [StanJulia/CmdStan.jl#46]
Hi, 

When running CmdStan.jl on my Windows 10 machine, I sometimes get 
`EBUSY: resource busy or locked` errors, especially when the previous model I was trying to fit failed to compile due to an error.

Is that an expected behaviour on Windows ?

Calling the garbage collector helps in some cases but not always.

Any help on how to avoid this locking issue would be helpful ! Thank you in advance !

**Comment by goedman** [comment]
It is certainly not expected nor desired behavior. In the past, a few years ago when I still had an old pc running Windows, I have seen problems with (removing) tmp directories. Do you see just above error or more info? Is there any info in the build or run logs?

**Comment by virgodi** [comment]
It’s just the above error. It occurs either when I’m trying to remove the tmp folder where the Stan model gets compiled or when I try to run a new Stan model in the same directory.

**Comment by goedman** [comment]
In the REPL, when you do:
```
tmp=mktempdir()
rm(tmp)
```
does that work?

**Comment by virgodi** [comment]
Sometimes using the garbage collector it will work, others the only solution is to shut down Julia...

**Comment by goedman** [comment]
You mean above 2 lines don't always work in a fresh REPL?

**Comment by virgodi** [comment]
They will only work 100% of the time, if I shut down all Julia instances and open a new repl.

**Comment by goedman** [comment]
Hmm, that looks like a Julia problem. For other reasons (testing on Travis) I am considering switching to mktempdir() and was hoping that would solve this issue as well. I'll try a few Google searches for mktempdir + Julia + Windows.

**Comment by goedman** [comment]
CmdStan 5.0.5 only uses 'proper' temporary directories. It doesn't solve the above mentioned Travis problem and I don't like it (I would like to keep the .csv files in a subdirectory of the working directory, not somewhere in a temp directory with very difficult paths).

Would you mind trying if this helps for your problem before I revert it back?

**Comment by goedman** [comment]
I'll go ahead and close this issue for now. CmdStan v5.1.0 (once released) now has a feature to create the tmp directories in a proper place.

**Comment by stelmo** [comment]
Hi there, I am having the same problem with a recently installed CmdStan v5.1.0. I am also running a windows 10 machine and get the error `ERROR: LoadError: IOError: unlink: resource busy or locked (EBUSY)` when I try to modify a stan problem I have already run once. I can make a tmp directory and delete it without issues though. Is there a way around this issue?

**Comment by goedman** [comment]
Would you mind sending me the script you are using? Or a simplified MWE where this happens? Thanks,
Rob

**Comment by stelmo** [comment]
Sure thing, here it is. Also, even when I quit and restart julia I get the same error. I need to manually delete the contents of the tmp folder while julia is "off" before I can run the julia script again (then it works beautifully). 

> using CmdStan, StanDataFrames, StatsPlots
> const linstanmodel = "
> data {
>   int<lower=0> N;
>   vector[N] x;
>   vector[N] y;
> }
> parameters {
>   real alpha;
>   real beta;
>   real<lower=0> sigma;
> }
> model {
>     y ~ normal(alpha + beta*x, sigma);
>     alpha ~ uniform(0, 2);
>     beta ~ normal(120, 50);
>     sigma ~ uniform(0, 1);
> }
> "
> 
> stanmodel = Stanmodel(name="linfit", model=linstanmodel, num_samples=10000, num_warmup=2000, thin=2)
> lindata = Dict("N" => 5, "x" => [0.016, 0.026, 0.029, 0.032, 0036], "y" => [3.788, 3.25, 13.48, 9.83, 5.54])
> 
> rc, chns, cnames = stan(stanmodel, lindata, pwd(), CmdStanDir=CMDSTAN_HOME)
> describe(chns)
>

**Comment by goedman** [comment]
Yes, it is a really weird problem. Can you try (see the note in the comment of what I'm trying here):
```
using CmdStan

linstanmodel = "
  data {
  int<lower=0> N;
  vector[N] x;
  vector[N] y;
  }
  parameters {
  real alpha;
  real beta;
  real<lower=0> sigma;
  }
  model {
  y ~ normal(alpha + beta*x, sigma);
  alpha ~ uniform(0, 2);
  beta ~ normal(120, 50);
  sigma ~ uniform(0, 1);
}"

# Note the addition of the tmpdir argument in the stanmodel call.

stanmodel = Stanmodel(name="linfit", model=linstanmodel, num_samples=10000, 
  num_warmup=2000, thin=2, tmpdir=mktempdir())
  
lindata = Dict("N" => 5, 
  "x" => [0.016, 0.026, 0.029, 0.032, 0036], 
  "y" => [3.788, 3.25, 13.48, 9.83, 5.54])

rc, chns, cnames = stan(stanmodel, lindata, pwd(), CmdStanDir=CMDSTAN_HOME)

describe(chns)
```

**Comment by stelmo** [comment]
It works! Thank you very much!!!

**Comment by goedman** [comment]
Thank you for trying. The big disadvantage of this approach (using a 'proper' temporary directory) is that each run the model is compiled. I'll think a bit about if this can be somehow avoided.
