### ISSUE TITLE
different RNG seed per chain

### ISSUE THREAD

**Issue by sdewaele** [StanJulia/CmdStan.jl#49]
As far as I known, currently I can only supply a single preset Random Number Generator (RNG) seed per chain, using `Stanmodel`:
````
  random = CmdStan.Random(4855748)
  sm = Stanmodel(Sample(),model=model,random=random,nchains=4)
````
The issue is that this introduces a dependency between the chains, because `4855748` is used as seed for all chains. I would like to be able to provide a different seed per chain.

Perhaps the `stan` function can accept an `Vector{Random}` as an input? I would propose that if `nchains>1`, this would be required, as I think it is preferred to use a different RNG seed per chain.

Similarly, if no RNG seed is provided in `Stanmodel`, each chain should get its own randomly generated seed. Currently, all chains get assigned the same seed.

**Comment by goedman** [comment]
Thanks for the suggestion. I’ll take a look tomorrow.

**Comment by goedman** [comment]
Stijn, my reading of this section of the manual (page 56 of cmdstan 2.19.1 guide) is that a value for seed < 0 will generate a new random number based on the time (and thus different for each chain each time the simulation is run).  For a seed >= 0 it will use that value as the starting seed for generating a random value for each chain (I have always assumed in this case that the starting points for each chain is reproducible). 

I did a quick test running the same simulation twice and looking at the first 4 draws:
```
# Stanmodel(..., random=Random(seed=12345, ...)

-8.08326,0.905325,0.95203,1,3,0,9.45865,0.467571
-7.65415,1,0.95203,1,3,0,8.01836,0.357945
-8.16736,0.899423,0.95203,2,3,0,8.43231,0.480011
-8.38065,0.705495,0.95203,2,7,0,10.0603,0.185466

-8.08326,0.905325,0.95203,1,3,0,9.45865,0.467571
-7.65415,1,0.95203,1,3,0,8.01836,0.357945
-8.16736,0.899423,0.95203,2,3,0,8.43231,0.480011
-8.38065,0.705495,0.95203,2,7,0,10.0603,0.185466

# random=Random(seed-1)

-9.8766,0.388116,1.1477,1,1,0,12.3969,0.634822
-8.79777,1,1.1477,2,3,0,9.79193,0.55174
-8.26869,1,1.1477,2,3,0,8.633,0.195535
-7.92081,1,1.1477,2,3,0,8.16238,0.439679

-7.66954,0.985616,0.952017,1,3,0,7.89924,0.367956
-8.56392,0.870854,0.952017,2,3,0,8.57857,0.171053
-8.94146,0.982104,0.952017,2,3,0,9.01102,0.146988
-8.2701,1,0.952017,1,1,0,8.84067,0.195401
```

Currently the CmdStan.jl setup indeed does not allow you to directly specify a fixed seed value for each chain (I don't think the cmdstan binary supports that).

Do you agree with the above interpretation? If not, I can certainly check my understanding with the Stan team.

Best,
Rob

**Comment by sdewaele** [comment]
Thanks! It could be that cmdstan does not support that, I have not looked into that. It would definitely be nice to have!

**Comment by goedman** [comment]
In a practical sense, by specifying a positive seed value you are guaranteed that all 4 chains each time start with the same (per chain different though) seed value while a negative seed value (the default) will always generate different starting seed values for each chain. Isn't a positive seed very close to what you are requesting?

**Comment by sdewaele** [comment]
If that is the case, then yes, I’m good. I was under the impression that each chain was using the same seed in that case. If they are different across chains I’m happy and nothing needs to change.

When I look at the log files for different chains,  they do show the same seed value. Does cmdstan actually vary the used seed internally? I could not find that in the docs.

**Comment by goedman** [comment]
Wouldn't otherwise the chains be identical (like in the above example where I set the seed to 12345 and run the simulation twice)? Chain 1 in the first run is identical to chain 1 in the second run, but different from chains 2, 3 and 4 in both runs.
