### ISSUE TITLE
Identical data for different chains

### ISSUE THREAD

**Issue by sdewaele** [StanJulia/CmdStan.jl#50]
The motivation for running several chains is to explore the posterior for __the same data__ from different starting points. Therefore, I propose to remove the possibility to provide different data sets for different chains in `stan`.

**Comment by goedman** [comment]
Thank you for your help in improving CmdStan.jl. I've often wondered about this feature. I'll remove it before releasing CmdStan.jl v"5.1.0" together with your other suggestions and some documentation updates. I'm hoping #49 and #50 will be fixed on master tomorrow evening (MDT time).

**Comment by goedman** [comment]
It has been a while since I wrote this part of CmdStan.jl (at that point Stan.jl, is it already about 5 years ago???) and I think my reasoning was twofold:

1. If one would toss a coin 10 times and finds heads came up 3 times the order should not matter.
2. Additionally, this option maybe allows e.g. testing the sensitivity of the inference against variations in (generated) sequences of observations.

This is more 'thin ice' stuff (at least for me, I think I should run it by the Stan folks) but I'm certainly interested in views as you express above. I have had suggestions in the past to at least make a single data Dict the 'natural' way to define the data (and incorporated that).

Thanks for your help,
Rob

**Comment by sdewaele** [comment]
Sometimes it is better not to provide an option, if it can easily be used wrongly. At least I would make it the natural option, as you say. This could e.g. be achieved by allowing a single dictionary as data argument instead of an array of dictionaries. Once that is in place I’d also recommend to remove it from the demos for the same reason.

I’m happy to chip in, e.g. by removing the different data sets from the examples if that helps.

**Comment by goedman** [comment]
Accepting a single dictionary (#28) is supported. Based on your feedback I have also added a similar note in the updated Walkthrough documentation. Any help with going over the examples is very welcome! You can make a PR or I can give you member access to StanJulia.

**Comment by sdewaele** [comment]
When I try to sample from a model using identical data (a single dict, not an array), with different initial values (a vector of Dicts), I get this error:
```
ERROR: LoadError: MethodError: no method matching update_R_file(::String, ::Array{Dict{String,Any},1})
Closest candidates are:
  update_R_file(::String, ::Dict{String,T}) where T at /home/sdwaele/.julia/dev/CmdStan/src/utilities/create_r_files.jl:52
Stacktrace:
 [1] #stan#4(::Array{Dict{String,Any},1}, ::Bool, ::Bool, ::String, ::Bool, ::Bool, ::Function, ::Stanmodel, ::Dict{String,Any}, ::String) at /home/sdwaele/.julia/dev/CmdStan/src/main/stancode.jl:164
```

I suspect the problem might be caused by the fact that line 155 looks at the type of `data`, then does something different for `init`? Should it perhaps check the type of `init` instead?
```
      if typeof(data) <: Array
```

**Comment by goedman** [comment]
Definitely a bug. Both typeof() tests should check ‘init’, not ‘data’. I guess this is only tested in the BernoulliInitTheta example where data and init both were arrays of length 4. I’m not behind my laptop tight now but will fix it later today.

Initially I was confused about your question as for init what you’re defining is a range for initial values (e.g by specifying theta=0.3, the range is -0.3 to 0.3) so allowing an array of Dicts there is maybe not very useful.

**Comment by goedman** [comment]
Should be fixed on master. I've left this as a testcase in bernoulliinittheta2.jl for now. As this is not a good example I might move it to the test directory.

**Comment by sdewaele** [comment]
Thanks for the bug fix. That works!

A range for the parameter is set only when a numerical value is given as a value for `init` in the model command line arguments. When a file is provided in the (which is generated when `init` is a Dict), they are used as starting value for the chain. That is how an array of Dicts can be used in a meaningful way. With the knowledge that I have about my model I can draw better starting points than the default random starting points.

I'm happy to update the examples to use the same data as a starting point. Otherwise, this issue can be closed as far as I'm concerned. Thanks again!

**Comment by goedman** [comment]
Aaah, that was a subtlety I'd missed. Thanks for pointing it out. 

If you're willing to update the examples, that would be great. I've seen them so often, tend to be blind to obvious way to improve them. 

Your two threads/issues certainly have helped me on what I think of as CmdStan.jl v6 which I'm working on (currently named StanSample.jl). Still in very early stage, but hopefully later this year.

I'll close this issue for now. Thanks for your help!

**Comment by goedman** [comment]
Hi Stijn,

Just to be complete, Michael Betancourt wrote (on my query):
```
If an init file is provided then each parameter name is queried in that file and if found
then the value in the file is used to initialize that parameter. If the parameter name is
not found then the quoted random initialization procedure is used.
```
which confirms what you pointed out and explains the earlier part of that section of the cmdstan guide:
```
Initialization is only applied to parameters defined in the parameters block. Any initial values supplied for transformed parameters or generated quantities are ig- nored.

init= Initialization method:

• real number x > 0 initializes randomly between [-x, x]; • 0 initializes to 0;
• non-number interpreted as a data file

Validvalues: All (Defaults to 2)
```

Currently CmdStan has no way of specifying a different value for the default of 2 (presumably for all parameters). I could do that e.g. with an Init(init::Number) type constructor or per chain using an array.
I'll think about it, no one ever asked for it ...
