### ISSUE TITLE
Pull request solving bug with Variational method

### ISSUE THREAD

**Issue by fargolo** [StanJulia/CmdStan.jl#54]
`stancode.jl` was inadequately calling `model.method.save_warmup` even with `model.method` `Variational` type.

Fixed by type checking with `isa(model.method,Sample)` before calling it.

https://github.com/StanJulia/CmdStan.jl/pull/53

**Comment by goedman** [comment]
Thank you very much for reporting this issue. I created this problem when I switched to MCMCChains.

On master I've done it slightly differently in that I've combined (prefix-ed) the test you'd updated.
