### ISSUE TITLE
Use logging instead of print

### ISSUE THREAD

**Issue by sethaxen** [StanJulia/CmdStan.jl#63]
There are a few instances where CmdStan prints to stdout. It would be convenient if the standard `Logging` macros were instead used (`@info`, `@warn`, etc). Then users could opt out of the messages without redirecting stdout. This is especially useful when running CmdStan in a documented example.

**Comment by goedman** [comment]
Hi Seth, seems like a good suggestion. I’ll have a look how much effort is involved as I’m pretty busy at the moment.

**Comment by sethaxen** [comment]
I'm happy to submit a PR if you'd like.

**Comment by goedman** [comment]
Absolutely! Thanks.

**Comment by goedman** [comment]
Seth, are you still considering making a PR?

**Comment by sethaxen** [comment]
Sorry @goedman , this PR became a lower priority. I probably won't get to it immediately.
