### ISSUE TITLE
Incorporate Sumatra into StanJulia workflow

### ISSUE THREAD

**Issue by bparbhu** [StanJulia/CmdStan.jl#7]

**Comment by goedman** [comment]
The current proposal is:

1. CmdStan.jl generate an Array as output.
2. StanDataFrames generates a DataFrame from the Array.
3. StanMamba converts the Array to a Mamba.Chains object, which opens up Mamba plots using Gadfly and Mamba diagnostics.
1. StanFeather was intended to store the CmdStan.jl output for later retrieval. Feather, Sumatra, and Arrow are all options we need to think about and choose one option?
1. StanPlotsRecipes is a Plots route, maybe using StanDataFrames as it’s basis?
