### ISSUE TITLE
A new release that supports MCMCChains 1.0

### ISSUE THREAD

**Issue by mohamed82008** [StanJulia/CmdStan.jl#76]
Hi Rob,

Does CmdStan support MCMCChains 1.0 already? If so, can we get a new release? Thank you.

**Comment by goedman** [comment]
Hi Mohamed,

Working on it! The plan is to leave the MCMCChains.Chains objects sorted when they are created in CmdStan. Hopefully Travis gets back up, not sure what's happening there.

Best,
Rob

**Comment by goedman** [comment]
v5.5 just got released.

**Comment by mohamed82008** [comment]
Cool! Thanks for the super prompt response!
