### ISSUE TITLE
Unused project dependencies resulting in long compilation time

### ISSUE THREAD

**Issue by sdewaele** [StanJulia/CmdStan.jl#78]
There are some dependencies in CmdStan that may not be needed, e.g. `StatsPlots` and `Documenter`, there may be more. If this is correct, it would be great if they could be removed as dependencies to reduce download and compilation time for the package. Both are pretty 'heavy' dependencies.

In case e.g. `StatsPlots` is needed only for testing, it can be added as a separate [testing dependency](https://julialang.github.io/Pkg.jl/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above-1). Although probably it is also not required for testing.

**Comment by goedman** [comment]
For now I will close the issue. CmdStan.jl v6 has removed many used and unused dependencies.
