### ISSUE TITLE
Get cmdstan to work with Linuxbrew for Linux users

### ISSUE THREAD

**Issue by bparbhu** [StanJulia/CmdStan.jl#8]
We need to use Linuxbrew to install cmdstan for our Linux Users. Also this method may work for Windows users who may also be using the Linux subsytem for Windows 10

**Comment by goedman** [comment]
Should we leave this item open then?

**Comment by bparbhu** [comment]
I think it's fine to close it for now.
When I originally created the issue I wasn't sure if there was a way to
install CmdStan with Linuxbrew outside of Julia.
Though there is a Linuxbrew.jl it hasn't been maintained in a year. So when
it becomes updated we can add syntax to account for that specific Julia
package in the
way that you have included Homebrew.jl syntax.

**Comment by bparbhu** [comment]
I think it's fine to close it for now. 
When I originally created the issue I wasn't sure if there was a way to install CmdStan with Linuxbrew outside of Julia.
Though there is a Linuxbrew.jl it hasn't been maintained in a year. So when it becomes updated we can add syntax to account for that specific Julia package in the
way that you have included Homebrew.jl syntax.
