### ISSUE TITLE
Remove Documenter

### ISSUE THREAD

**Issue by Byrth** [StanJulia/CmdStan.jl#83]
This is not a big deal of course because the package itself has pretty common dependencies, but Documenter functionality is not used by CmdStan.jl and thus the package isn't really a dependency.

I on Julia Slack's #helpdesk and got a green checkmark (which I take to be agreement) when I proposed that the most Julian way to record dependencies for your `docs/make.jl` script is to create a Project.toml in the docs/ folder that lists Documenter as a dependency (as well as the main package and any other dependencies) with a `[compat]` tag for the right versions. This way when you want to generate documentation you `cd()` to the directory and `]activate .` the environment before running make.jl.

I could see this moving to a different `[extras]` target in the future, but at present it might be good to remove it as a dependency.

**Comment by goedman** [comment]
Hi @Byrth,

Thank you, removed it and is in the queue to be merged as CmdStan.jl v6.0.1.

Best,
Rob

**Comment by Byrth** [comment]
Nice! Amazingly quick again. Thanks, Rob.

**Comment by goedman** [comment]
You're welcome. Please, let me know if you come across any other issues!

**Comment by Byrth** [comment]
Will do! Going to close this one because my version just updated
