### ISSUE TITLE
CmdStan release

### ISSUE THREAD

**Issue by cpfiffer** [StanJulia/CmdStan.jl#89]
Could you tag a release for 0.6.3?

**Comment by goedman** [comment]
Hi Cameron,

Done, although I wasn't sure why. MCMCChains is now behing Requires in CmdStan. I haven't had a lot of time to test the new version(s) but hopefully will. 

Best,
Rob

**Comment by cpfiffer** [comment]
The only reason was that there was a `CSV`/`Parsers`/`CmdStan` nightmare that was screwing up our CI for some weird reason -- thanks!
