### ISSUE TITLE
Get cmdstan.jl to work for Windows 10 and above users.

### ISSUE THREAD

**Issue by bparbhu** [StanJulia/CmdStan.jl#9]
We need to make sure that Windows users can use the cmdstan.jl package that wraps around cmdstan.

**Comment by goedman** [comment]
We really would need someone that uses Windows all the time in the team.

**Comment by bparbhu** [comment]
Yeah I agree. I use Windows a lot but I went with Ubuntu because I figured it would be easier to work with CmdStan.
