### ISSUE TITLE
Artifacts compatibility

### ISSUE THREAD

**Issue by ChrisRackauckas** [StanJulia/CmdStan.jl#92]
It would be great if CmdStan.jl provided the executable via artifacts so that way it doesn't need to be installed by the user.

**Comment by goedman** [comment]
Using artifacts is definitely of interest to me (although I haven't had time to really read through the docs).

I do wonder how many versions would be needed for the platforms (Windows, several Linux versions, MacOS, and ...). Even on MacOS I regularly need to recompile for toolchain updates.

The other issue is building and testing the artifacts.

But first I need to read the docs!
