### ISSUE TITLE
Minor release for DataFrames 0.21

### ISSUE THREAD

**Issue by itsdfish** [StanJulia/CmdStan.jl#94]
Hi Rob-
I was wondering if you would be able to release a version of CmdStan.jl that is compatible with DataFrames 0.21? Right now it is blocking me from updating some projects. Thanks!

**Comment by goedman** [comment]
Hi Chris, hopefully should be merged in the next 15 mins or so.

I was holding off because wanted to combine it with the DiffEqBayes updates, but that will take a few more days to wrap up.

**Comment by goedman** [comment]
Done!

**Comment by itsdfish** [comment]
Thanks, Rob!
